name: bitcoinrain

#root: ~/inersha/projects/bitcoinrain/stream-php/
#windows:
#  - server: php stream.php
#  - websocketd: bash websocketd.sh
#  - client: ruby client.rb

root: ~/inersha/projects/bitcoinrain/stream-ruby/
windows:
  - server: ruby server.rb
  - websocketd: bash websocketd.sh
  - client: ruby client.rb
